/*
 * Decompiled with CFR 0_122.
 */
package opencellar.framework;

import opencellar.framework.BaseItem;
import opencellar.framework.Cellar;
import opencellar.framework.CellarObject;
import opencellar.framework.ObjectType;
import opencellar.framework.Rack;
import opencellar.framework.RackBuilder;
import opencellar.framework.RackItem;

public final class TemplateFactory {
    public static void fillTemplate(Cellar cellar) {
        if (cellar == null) {
            throw new IllegalArgumentException("cellar == null");
        }
        BaseItem item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Alsace");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Bourgogne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Vall\u00e9e de la Loire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Jura / Savoie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Provence");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Languedoc-Roussillon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Bordeaux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Sud-Ouest");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Beaujolais");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Rh\u00f4ne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Champagne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Autres");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Area);
        item.setName("Corse");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("20 cl");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("35 cl");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("37,5 cl");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("40 cl");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("62 cl");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("72 cl");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("75 cl");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("77,5 cl");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("80 cl");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("1,5 l (magnum)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("1,6 l (magnum)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("3 l (double magnum)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("3,2 l (j\u00e9roboam)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("4 l (j\u00e9roboam)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("4,8 l (r\u00e9hoboam)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("6 l (imp\u00e9riale)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("6,4 l (mathusalem)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("9,6 l (salmanazar)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("12,8 l (balthazar)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.BottleType);
        item.setName("16 l (nabuchodonosor)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Category);
        item.setName("Vins");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Category);
        item.setName("Bieres");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Category);
        item.setName("Champagnes");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Category);
        item.setName("Spiritueux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Category);
        item.setName("Aperitifs");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("1er Cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("1er Cru Classe");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("1er Cru Superieur");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("1er Grand Cru A");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("1er Grand Cru B");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("1er Grand Cru Classe");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("2\u00e8me Cru Classe");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("3\u00e8me Cru Classe");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("2\u00e8me Cru Classe");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("4\u00e8me Cru Classe");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("5\u00e8me Cru Classe");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("Cru Artisan");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("Cru Bourgeois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("Cru Bourgeois Exceptionnel");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("Cru Bourgeois Superieur");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("Cru Classe");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("Grand Cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("Grand Cru Bourgeois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("Grand Cru Classe");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("Vin de table");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("Vin de pays");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Classification);
        item.setName("A.O.V.D.Q.S.");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Afrique du Sud");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Allemagne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Argentine");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Australie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Autriche");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Bulgari");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Br\u00e9sil");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Canada");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Chili");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Chine");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Chypre");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Cor\u00e9e du Sud");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Espagne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Etats-Unis");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("France");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("G\u00e9orgie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Hongrie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Inde");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Israel");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Italie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Japon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Liban");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Maroc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Mexique");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Nouvelle Z\u00e9lande");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("P\u00e9rou");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Portugal");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Slov\u00e9nie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Tunisie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Ukraine");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Country);
        item.setName("Uruguay");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ajaccio");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Aloxe-corton");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace klevener de heiligenstein");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace \"edelzwicker\"");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace \"gentil\"");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace (chasselas)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace (gewurztraminer)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace (muscat)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace (pinot, pinot blanc ou klevner)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace (pinot gris)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace (pinot noir)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace (riesling)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace (sylvaner)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace (tokay-pinot gris)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Alsace grand cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Anjou-coteaux de la loire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Anjou-gamay");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Anjou mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Anjou-villages");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Anjou-villages-brissac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Arbois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Arbois pupillin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Arbois mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Auxey-duresses");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Provence");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Banyuls");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Banyuls grand cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Barsac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("B\u00e2tard-montrachet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("B\u00e9arn");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Beaujolais");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Beaujolais-villages");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Beaumes de venise");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Beaune");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bergerac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bergerac sec");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bergerac ros\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bienvenues-b\u00e2tard-montrachet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Blagny");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Blanquette de limoux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Blanquette de limoux m\u00e9thode ancestrale");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Blaye");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bonnes-mares");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bonnezeaux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bordeaux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bordeaux clairet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bordeaux-c\u00f4tes de francs");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bordeaux ros\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bordeaux sec");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bordeaux sup\u00e9rieur");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne aligot\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne aligot\u00e9 bouzeron");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne c\u00f4te chalonnaise");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne c\u00f4te d'auxerre");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne grand ordinaire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne hautes-c\u00f4tes de beaune");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne hautes-c\u00f4tes de nuits");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne ordinaire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne passetoutgrain");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne ros\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgogne vezelay");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bourgueil");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Bouzeron");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Brouilly");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Buzet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cabard\u00e8s");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cabernet d'anjou");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cabernet de saumur");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cadillac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cahors");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Canon-fronsac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cassis");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00e9rons");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chablis");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chablis grand cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chablis premier cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chambertin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chambertin clos-de-b\u00e8ze");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chambolle-musigny");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Champagne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Champagne grand cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Champagne premier cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chapelle-chambertin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Charlemagne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Charmes-chambertin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chassagne-montrachet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ch\u00e2teau-chalon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ch\u00e2teau-grillet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ch\u00e2teaumeillant");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ch\u00e2teauneuf-du-pape");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ch\u00e2tillon-en-diois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ch\u00e9nas");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chevalier-montrachet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cheverny");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chinon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chiroubles");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Chorey-l\u00e8s-beaune");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Clairette de bellegarde");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Clairette de die");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Clairette du languedoc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Clos de la roche");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Clos de tart");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Clos de vougeot");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Clos des lambrays");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Clos saint-denis");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Collioure");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Condrieu");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Corbi\u00e8res");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Corbi\u00e8res-boutenac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cornas");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Corton");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Corton charlemagne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Costi\u00e8res de n\u00eemes");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4te de beaune");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4te de brouilly");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4te de nuits-villages");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4te roannaise");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4te-r\u00f4tie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux champenois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux d'aix-en-provence");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux d'ancenis");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux de die");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux de l'aubance");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux de pierrevert");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux de saumur");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du giennois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du languedoc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du layon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du layon Beaulieu-sur-Layon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du layon chaume");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du layon chaume premier cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du layon Faye-d'Anjou");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du layon Rablay-sur-Layon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du layon Rochefort-sur-Loire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du layon Saint-Aubin-de-Luigne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du layon Saint-Lambert-du-Lattay");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du loir");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du lyonnais");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du quercy");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux du tricastin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vall\u00e9e de la Loire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Coteaux varois-en-provence");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes d'auvergne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes d'auvergne-chanturgue");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de beaune-villages");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de bergerac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de blaye");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de bordeaux saint-macaire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de bourg");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de castillon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de duras");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de la malep\u00e8re");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de millau");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de montravel");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de provence");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de saint-mont");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes de toul");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du brulhois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du forez");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du frontonnais");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du jura");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du jura mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du luberon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du marmandais");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Beaumes-de-Venise");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Cairanne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages chusclan");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Laudun");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Rasteau");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Roaix");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Rochegude");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Rousset-les-Vignes");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Sablet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Saint-Gervais");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Saint-Maurice");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Saint-Pantal\u00e9on-les-vignes");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages S\u00e9guret");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Valr\u00e9as");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Vinsobres");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du rh\u00f4ne-villages Visan");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du roussillon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du roussillon-les aspres");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du roussillon-villages");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du ventoux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("C\u00f4tes du vivarais");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cour-cheverny");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cr\u00e9mant d'alsace");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cr\u00e9mant de bordeaux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cr\u00e9mant de bourgogne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cr\u00e9mant de die");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cr\u00e9mant de limoux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cr\u00e9mant de loire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cr\u00e9mant du jura");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Cr\u00e9py");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Criots-b\u00e2tard-montrachet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Crozes-hermitage");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ech\u00e9zeaux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Entre-deux-mers");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Entre-deux-mers haut-benauge");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Languedoc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Fiefs vend\u00e9ens");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Fitou");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Fixin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Fleurie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Floc de gascogne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Fronsac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Sud-Ouest");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Gaillac premieres c\u00f4tes");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Gevrey-chambertin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Gigondas");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Givry");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Grands-\u00e9chezeaux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Graves");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Graves-de-vayres");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Graves sup\u00e9rieures");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Griotte-chambertin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Gros-plant du pays nantais");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Haut-m\u00e9doc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Haut-montravel");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Haut-poitou");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Hermitage");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Iroul\u00e9guy");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Juli\u00e9nas");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Juran\u00e7on");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Juran\u00e7on sec");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("La grande rue");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("La t\u00e2che");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ladoix");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Lalande-de-pomerol");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Latrici\u00e8res-chambertin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Lavilledieu");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Les baux-de-provence");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("L'\u00e9toile");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("L'\u00e9toile mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Limoux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Lirac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Loupiac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Lussac saint-\u00e9milion");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("M\u00e2con");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("M\u00e2con-sup\u00e9rieur");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("M\u00e2con-villages");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Macvin du jura");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Madiran");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Maranges");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Maranges premier cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Marcillac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Margaux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Marsannay");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Marsannay ros\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Maury");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Mazis-chambertin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Mazoy\u00e8res-chambertin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("M\u00e9doc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Menetou-salon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Mercurey");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Meursault");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Minervois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Minervois-la-livini\u00e8re");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Monbazillac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Montagne-saint-\u00e9milion");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Montagny");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Month\u00e9lie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Montlouis");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Montlouis mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Montlouis p\u00e9tillant");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Montrachet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Montravel");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Morey saint-denis");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Morgon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Moselle");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Moulin-\u00e0-vent");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Moulis");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscadet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscadet c\u00f4tes de grandlieu");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscadet s\u00e8vre-et-maine");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscadet coteaux de la loire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscat de beaumes-de-venise");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscat de frontignan");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscat de lunel");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscat de mireval");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscat de rivesaltes");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscat de saint-jean-de-minervois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Muscat du cap corse");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Musigny");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pacherenc du vic-bilh");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pacherenc du vic-bilh sec");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Palette");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Patrimonio");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pauillac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("P\u00e9charmant");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pernand-vergelesses");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pessac-l\u00e9ognan");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Petit chablis");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pineau des charentes");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pomerol");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pommard");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pommeau de normandie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pouilly-fuiss\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pouilly-fum\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pouilly-loch\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pouilly-sur-loire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Pouilly-vinzelles");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Premi\u00e8res c\u00f4tes de blaye");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Premi\u00e8res c\u00f4tes de bordeaux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Puisseguin-saint-\u00e9milion");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Puligny-montrachet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Quarts de chaume");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Quincy");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("R\u00e9gni\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Reuilly");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Richebourg");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Rivesaltes");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Roman\u00e9e (La)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Roman\u00e9e-conti");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Roman\u00e9e saint-vivant");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ros\u00e9 d'anjou");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ros\u00e9 de loire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ros\u00e9 des riceys");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Rosette");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Roussette de savoie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Roussette du bugey");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Ruchottes-chambertin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Rully");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-amour");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-aubin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-chinian");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-chinian Berlou");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-chinian Roquebrun");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-\u00e9milion");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-\u00e9milion grand cru");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-est\u00e8phe");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-georges-saint-\u00e9milion");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-joseph");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-julien");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-nicolas-de-bourgueil");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-p\u00e9ray");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-p\u00e9ray mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-pour\u00e7ain");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-romain");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint sardos (AOVDQS)");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saint-v\u00e9ran");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Sainte-croix-du-mont");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Sainte-foy-bordeaux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Sancerre");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Santenay");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saumur");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saumur mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saumur-champigny");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Saussignac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Sauternes");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Sauvignon de saint-bris");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Savenni\u00e8res");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Savigny-l\u00e8s-beaune");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Seyssel");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Seyssel mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Tavel");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Touraine");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Touraine amboise");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Touraine azay-le-rideau");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Touraine mesland");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Touraine mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Touraine noble jou\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Touraine p\u00e9tillant");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Tursan");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vall\u00e9e du Rh\u00f4ne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Valen\u00e7ay");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vin de savoie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vin de savoie mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vin de savoie p\u00e9tillant");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vin du bugey");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vins de corse");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vins de l'orl\u00e9annais");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vins d'entraygues et du fel");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vins d'estaing");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vins du thouarsais");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vir\u00e9-cless\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Volnay");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Volnay santenots");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vosne-roman\u00e9e");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vougeot");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vouvray");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vouvray mousseux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.Name);
        item.setName("Vouvray p\u00e9tillant");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Altesse");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Aramon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Arbanne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Arbois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Arrufiac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Auxerrois");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Barbaroux");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Baroque");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("B\u00e9quignol");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Blanc Fum\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Blanquette");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Bouchet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Bourboulenc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Breton");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Cabernet-franc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Cabernet-sauvignon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Carignan");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Chardonnay");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Chasselas");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Chenin blanc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Chenin noir");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Cinsault");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Clairette");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Colombard");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Cot");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Courbu");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Counoise");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Cruchen");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Duras");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Durif");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Fer");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Fer-Servadou");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Folle Blanche");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Frontignan");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Gamay");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Gewurtztraminer");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Grenache");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Grenache Blanc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Gringet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Grolleau");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Gros-Lot");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Gros Manseng");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Gros Plant");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Jacqu\u00e0re");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Klevner");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Knipperl\u00e9");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Macabeu");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Malbec");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Malvoisie");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Manicle");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Mansenc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Marsanne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Mauzac");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Melon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Menu Pineau");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Merlot");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Merlot Blanc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Meunier");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Mondeuse");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Mourv\u00e0dre");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Muscadelle");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Muscadet");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Muscadin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Muscat");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Muscat noir");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("N\u00e9grette");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Nielluccio");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Noirin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Oeillade Blanc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Pacherenc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Pascal");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Pecoultouar");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Petit Mansin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Petit Meslier");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Petit Verdot");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Picardan");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Picpoul");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Pineau d'Aunis");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Pineau de la Loire");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Pinot blanc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Pinot gris");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Pinot Meunier");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Pinot noir");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Poulsard");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Riesling");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Rolle");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Romorantin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Roussanne");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Roussette");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Sacy");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("St-Pierre");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Sauvignon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Savagnin");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Sciacarello");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("S\u00e9millon");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Sylvaner");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Syrah");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Tannat");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Terret");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Tibouren");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Traminer");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Tressalier");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Ugni-Blanc");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Vaccar\u00e0se");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Verdot");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Vermentino");
        item.save();
        item = (BaseItem)cellar.createItem(ObjectType.TypeOfWine);
        item.setName("Viognier");
        item.save();
        RackBuilder builder = new RackBuilder(cellar);
        builder.setName("Emplacement par d\u00e9faut");
        builder.save();
        int rows = builder.getRack().getRows();
        int columns = builder.getRack().getColumns();
        for (int i = 0; i < rows; ++i) {
            for (int j = 0; j < columns; ++j) {
                RackItem ri = builder.createItem(i, j);
                ri.save();
            }
        }
    }
}

