package net.jiniguru.roshan.ui.view.customer.b2b;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class B2CustomerViewDesign extends VerticalLayout {
	protected TextField search;
	protected Button add;
	protected Grid<net.jiniguru.roshan.backend.data.entity.B2Customer> list;
	protected VerticalLayout form;
	protected TextField id;
	protected TextField company;
	protected DateField enrollmentDate;
	protected TextField firstName;
	protected TextField lastName;
	protected TextField mobileNumber;
	protected TextField email;
	protected TextArea billAddress;
	protected TextArea deliveryAddress;
	protected TextField workNumber;
	protected TextField vatNumber;
	protected TextField brnNumber;
	protected ComboBox<java.lang.String> paymentAgreement;
	protected TextField coursedFollowed;
	protected TextArea note;
	protected ComboBox<java.lang.String> status;
	protected Button update;
	protected Button cancel;
	protected Button print;
	protected Button delete;

	public B2CustomerViewDesign() {
		Design.read(this);
	}
}
