package net.jiniguru.roshan.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainViewDesign extends HorizontalLayout {
	protected Label activeViewName;
	protected Button menuButton;
	protected CssLayout menu;
	protected Button storefront;
	protected Button dashboard;
	protected Button customers;
	protected Button bcustomers;
	protected Button dashboard11;
	protected Button dashboard111;
	protected Button dashboard1111;
	protected Button users;
	protected Button users1;
	protected Button products;
	protected Button inventory;
	protected Button logout;
	protected VerticalLayout content;

	public MainViewDesign() {
		Design.read(this);
	}
}
