package net.spark.backend.util;

public class WineSheetTemplate {
	public static String [] WINE = {"Pays/région",
	"Couleur", 
	"Format",
	"Appellation",   
	"Propriéte",
	"Millesime",
	"Classement",   
	"Encepagement",   
	"Apogée",
	"Nombre",   
	"Temperature de service",   
	"Provenance",
	"Caisse bois d'origine",   
	"Type de cave",
	"Lot de",
	"Niveau",
	"Etiquette",
	"TVA récupérable",
	"Cote du vin",
	"Prix de reserve",
	"Notes des critiques",
	"Remarque",
	"Type de stockage",
	"Photo",
	"Conseil du Pro"};
	public static String [] WINE_VALUE = {"France",
	"Rouge", 
	"75cl",
	"Appellation",   
	"Propriéte",
	"Millesime",
	"Classement",   
	"Encepagement",   
	"Apogée",
	"Nombre",   
	"Temperature de service",   
	"Provenance",
	"Caisse bois d'origine",   
	"Type de cave",
	"Lot de",
	"Niveau",
	"Etiquette",
	"15%",
	"Cote du vin",
	"Prix de reserve",
	"Notes des critiques",
	"Remarque",
	"Type de stockage",
	"local://range/p.png",
	"avec viandre rouge"};
}
